### ISSUE TITLE
Occasional Issue When Loading

### ISSUE THREAD

**Issue by aidenbull** [DanielPopOut/dockScreen#33]
Generally resolved by a refresh, but so we're aware of it.

![dockScreenIssue](https://github.com/DanielPopOut/dockScreen/assets/47465891/f56da90d-09b6-4d58-929f-e83865111410)

**Comment by DanielPopOut** [comment]
This only happens in dev mode and won't be in prod.
It's due to the difference in how date.toLocaleString is interpreted on the server side
As the text show you had a very specific case where the text was generate at 12:05Pm on the server and rendered at 12:06 in the browser
